name: Prepare BETA release

on:
  push:
    tags:
      - "beta[0-9]+"

jobs:
  build-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        configuration: [msvc-debug, msvc-release]
        enable_steam: [false]
        include:
          - enable_steam: true
            configuration: msvc-release
    name: 'build-windows [${{ matrix.configuration }}, steam: ${{ matrix.enable_steam }}]'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Install Conan
      run: pip install conan
    - name: Configure with CMakeSettings.json and build
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeSettingsJson
        cmakeSettingsJsonPath: '${{ github.workspace }}/CMakeSettings.json'
        useVcpkgToolchainFile: false
        buildDirectory: '${{ github.workspace }}/build'
        configurationRegexFilter: '${{ matrix.configuration }}'
        cmakeAppendedArgs: '-DSTORM_ENABLE_STEAM=${{ matrix.enable_steam }} -DSTORM_ENABLE_CRASH_REPORTS=ON'
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: storm-engine.${{ matrix.configuration }}-steam-${{ matrix.enable_steam }}
        path: build\${{ matrix.configuration }}\bin
    - name: Archive release
      uses: papeloto/action-zip@v1
      with:
        files: build\${{ matrix.configuration }}\bin
        recursive: true
        dest: storm-engine.${{ matrix.configuration }}-steam-${{ matrix.enable_steam }}.zip
    - name: Publish release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: storm-engine.${{ matrix.configuration }}-steam-${{ matrix.enable_steam }}.zip
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Upload debug symbols
      run: |
        npm install @sentry/cli
        ./node_modules/.bin/sentry-cli --auth-token ${{ secrets.SENTRY_AUTH_TOKEN }} upload-dif -o storm-devs -p storm-engine -t pe -t pdb "build\${{ matrix.configuration }}\bin"